dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0          # Local database
  path: ^1.9.0             # Path helper
  geolocator: ^11.0.0      # GPS access
  http: ^1.2.0             # Send data to Flask
  connectivity_plus: ^6.0.0 # Detect Wi-Fi/Mobile data
  workmanager: ^0.5.2      # Background task management